# ==============================================================================
# AFL GitHub Repository Credentials
# ==============================================================================

# CBAAS Business Service Repository
apiVersion: v1
kind: Secret
metadata:
  name: afl-github-repo-cbaas-business
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
    service: cbaas-business
    project: afl-cbaas-services
type: Opaque
stringData:
  type: git
  name: cbaas.business.git
  url: git@github.com:Africa-FinTech-Ltd/afl.service.cbaas.business.git
  insecure: "true"
  enableLfs: "true"
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDR9m5LmT9WcR9fSLxDFN6+DqTe3Sj2LCiu8DmG8BXQdAAAAJhjmeK/Y5ni
    vwAAAAtzc2gtZWQyNTUxOQAAACDR9m5LmT9WcR9fSLxDFN6+DqTe3Sj2LCiu8DmG8BXQdA
    AAAEBIvZdkr5ukGn+tTs0tJ5akp7hVOZJcNxvfTy0ad+P619H2bkuZP1ZxH19IvEMU3r4O
    pN7dKPYsKK7wOYbwFdB0AAAAEWFyZ29jZEA5amFwYXkuY29tAQIDBA==
    -----END OPENSSH PRIVATE KEY-----
---
# CBAAS Audit Service Repository
apiVersion: v1
kind: Secret
metadata:
  name: afl-github-repo-cbaas-audit
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
    service: cbaas-audit
    project: afl-cbaas-services
type: Opaque
stringData:
  type: git
  name: cbaas.audit.git
  url: git@github.com:Africa-FinTech-Ltd/afl.service.cbaas.audit.git
  insecure: "true"
  enableLfs: "true"
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDR9m5LmT9WcR9fSLxDFN6+DqTe3Sj2LCiu8DmG8BXQdAAAAJhjmeK/Y5ni
    vwAAAAtzc2gtZWQyNTUxOQAAACDR9m5LmT9WcR9fSLxDFN6+DqTe3Sj2LCiu8DmG8BXQdA
    AAAEBIvZdkr5ukGn+tTs0tJ5akp7hVOZJcNxvfTy0ad+P619H2bkuZP1ZxH19IvEMU3r4O
    pN7dKPYsKK7wOYbwFdB0AAAAEWFyZ29jZEE5amFwYXkuY29tAQIDBA==
    -----END OPENSSH PRIVATE KEY-----
---
# CBAAS Postings Service Repository
apiVersion: v1
kind: Secret
metadata:
  name: afl-github-repo-cbaas-postings
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
    service: cbaas-postings
    project: afl-cbaas-services
type: Opaque
stringData:
  type: git
  name: cbaas.postings.git
  url: git@github.com:Africa-FinTech-Ltd/afl.service.cbaas.postings.git
  insecure: "true"
  enableLfs: "true"
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDR9m5LmT9WcR9fSLxDFN6+DqTe3Sj2LCiu8DmG8BXQdAAAAJhjmeK/Y5ni
    vwAAAAtzc2gtZWQyNTUxOQAAACDR9m5LmT9WcR9fSLxDFN6+DqTe3Sj2LCiu8DmG8BXQdA
    AAAEBIvZdkr5ukGn+tTs0tJ5akp7hVOZJcNxvfTy0ad+P619H2bkuZP1ZxH19IvEMU3r4O
    pN7dKPYsKK7wOYbwFdB0AAAAEWFyZ29jZEE5amFwYXkuY29tAQIDBA==
    -----END OPENSSH PRIVATE KEY-----
---
# CBAAS API Gateway Service Repository
apiVersion: v1
kind: Secret
metadata:
  name: afl-github-repo-cbaas-apigateway
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
    service: cbaas-apigateway
    project: afl-cbaas-services
type: Opaque
stringData:
  type: git
  name: cbaas.apigateway.git
  url: git@github.com:Africa-FinTech-Ltd/afl.service.cbaas.apigateway.git
  insecure: "true"
  enableLfs: "true"
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDR9m5LmT9WcR9fSLxDFN6+DqTe3Sj2LCiu8DmG8BXQdAAAAJhjmeK/Y5ni
    vwAAAAtzc2gtZWQyNTUxOQAAACDR9m5LmT9WcR9fSLxDFN6+DqTe3Sj2LCiu8DmG8BXQdA
    AAAEBIvZdkr5ukGn+tTs0tJ5akp7hVOZJcNxvfTy0ad+P619H2bkuZP1ZxH19IvEMU3r4O
    pN7dKPYsKK7wOYbwFdB0AAAAEWFyZ29jZEE5amFwYXkuY29tAQIDBA==
    -----END OPENSSH PRIVATE KEY-----
---
# CBAAS Core Service Repository
apiVersion: v1
kind: Secret
metadata:
  name: afl-github-repo-cbaas-core
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
    service: cbaas-core
    project: afl-cbaas-services
type: Opaque
stringData:
  type: git
  name: cbaas.core.git
  url: git@github.com:Africa-FinTech-Ltd/afl.service.cbaas.core.git
  insecure: "true"
  enableLfs: "true"
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDR9m5LmT9WcR9fSLxDFN6+DqTe3Sj2LCiu8DmG8BXQdAAAAJhjmeK/Y5ni
    vwAAAAtzc2gtZWQyNTUxOQAAACDR9m5LmT9WcR9fSLxDFN6+DqTe3Sj2LCiu8DmG8BXQdA
    AAAEBIvZdkr5ukGn+tTs0tJ5akp7hVOZJcNxvfTy0ad+P619H2bkuZP1ZxH19IvEMU3r4O
    pN7dKPYsKK7wOYbwFdB0AAAAEWFyZ29jZEE5amFwYXkuY29tAQIDBA==
    -----END OPENSSH PRIVATE KEY-----
---
# CBAAS argocd Service Repository
apiVersion: v1
kind: Secret
metadata:
  name: afl-arocd-repo-cbaas-postings
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
    service: cbaas-argocd
    project: afl-cbaas-services
type: Opaque
stringData:
  type: git
  name: cbaas.argocd.git
  url: git@github.com:Africa-FinTech-Ltd/afl-devops-argocd.git
  insecure: "true"
  enableLfs: "true"
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDR9m5LmT9WcR9fSLxDFN6+DqTe3Sj2LCiu8DmG8BXQdAAAAJhjmeK/Y5ni
    vwAAAAtzc2gtZWQyNTUxOQAAACDR9m5LmT9WcR9fSLxDFN6+DqTe3Sj2LCiu8DmG8BXQdA
    AAAEBIvZdkr5ukGn+tTs0tJ5akp7hVOZJcNxvfTy0ad+P619H2bkuZP1ZxH19IvEMU3r4O
    pN7dKPYsKK7wOYbwFdB0AAAAEWFyZ29jZEE5amFwYXkuY29tAQIDBA==
    -----END OPENSSH PRIVATE KEY-----

# ==============================================================================
# Helm Repository Credentials
# ==============================================================================
---
# Bitnami Helm Repository
apiVersion: v1
kind: Secret
metadata:
  name: bitnami-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
    repo-type: helm
type: Opaque
stringData:
  type: helm
  name: bitnami
  url: https://charts.bitnami.com/bitnami
---
# Prometheus Community Helm Repository
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
    repo-type: helm
type: Opaque
stringData:
  type: helm
  name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
---
# Grafana Helm Repository
apiVersion: v1
kind: Secret
metadata:
  name: grafana-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
    repo-type: helm
type: Opaque
stringData:
  type: helm
  name: grafana
  url: https://grafana.github.io/helm-charts
---
# Ingress NGINX Helm Repository
apiVersion: v1
kind: Secret
metadata:
  name: ingress-nginx-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
    repo-type: helm
type: Opaque
stringData:
  type: helm
  name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
---
# Jetstack Helm Repository (Cert-Manager)
apiVersion: v1
kind: Secret
metadata:
  name: jetstack-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
    repo-type: helm
type: Opaque
stringData:
  type: helm
  name: jetstack
  url: https://charts.jetstack.io


  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |-
    registries:
      - name: SWR-HUAWEI
        api_url: https://swr.af-south-1.myhuaweicloud.com
        prefix: swr.af-south-1.myhuaweicloud.com
        ping: yes
        insecure: no
        credentials: pullsecret:argocd/registry-secret
