apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: argocd
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/ENVIRONMENT_NAME-eks-external-secrets"  # Will be patched
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: argocd
spec:
  provider:
    aws:
      service: SecretsManager
      region: AWS_REGION  # Will be patched by overlays
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{ .username | toString }}"
        password: "{{ .password | toString }}"
        host: "{{ .endpoint | toString }}"
        port: "{{ .port | toString }}"
        database: "{{ .dbname | toString }}"
  data:
    - secretKey: username
      remoteRef:
        key: pipeops/ENVIRONMENT_NAME/rds/credentials  # Will be patched
        property: username
    - secretKey: password
      remoteRef:
        key: pipeops/ENVIRONMENT_NAME/rds/credentials  # Will be patched
        property: password
    - secretKey: endpoint
      remoteRef:
        key: pipeops/ENVIRONMENT_NAME/rds/credentials  # Will be patched
        property: endpoint
    - secretKey: port
      remoteRef:
        key: pipeops/ENVIRONMENT_NAME/rds/credentials  # Will be patched
        property: port
    - secretKey: dbname
      remoteRef:
        key: pipeops/ENVIRONMENT_NAME/rds/credentials  # Will be patched
        property: dbname
