# Sample Application for demonstration
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-web-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: https://github.com/your-org/sample-web-app  # Update with your app repository
    targetRevision: HEAD
    path: k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
# External Secrets Store for AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: sample-app
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
# External Secret for Database Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: sample-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{ .username | toString }}"
        password: "{{ .password | toString }}"
        host: "{{ .endpoint | toString }}"
        port: "{{ .port | toString }}"
        database: "{{ .dbname | toString }}"
  data:
    - secretKey: username
      remoteRef:
        key: pipeops/prod/rds/credentials
        property: username
    - secretKey: password
      remoteRef:
        key: pipeops/prod/rds/credentials
        property: password
    - secretKey: endpoint
      remoteRef:
        key: pipeops/prod/rds/credentials
        property: endpoint
    - secretKey: port
      remoteRef:
        key: pipeops/prod/rds/credentials
        property: port
    - secretKey: dbname
      remoteRef:
        key: pipeops/prod/rds/credentials
        property: dbname
---
# Service Account for External Secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: sample-app
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/pipeops-prod-eks-external-secrets"  # Update with your account ID